name: debug
on:
  repository_dispatch:
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HELLO_AZURE_CREDENTIALS }}
      
